default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Martial@5009

development:
  <<: *default
  database: my_spents_development
  username: postgres
  password: Martial@5009

test:
  <<: *default
  database: my_spents_test

production:
  <<: *default
  database: my_spents_production
  username: my_spents
  password: <%= ENV["MY_SPENTS_DATABASE_PASSWORD"] %>
