default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_spents_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: my_spents_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: my_spents_production
  username: my_spents
  password: <%= ENV["MY_SPENTS_DATABASE_PASSWORD"] %>
